title: test title
description: test desc
baseurl: "/"
url: ""

email: test email
emailjoin: test emailjoin
twitter: test tweet
googlescholar: test google sch
orcid: test orcid
github: test git

# Build settings
markdown: kramdown
permalink: /:categories/:title/

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: "\n\n"

# Theme settings
compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all

sass:
  sass_dir: assets/_sass
  style: compressed


images: '/assets/images'
images-people: '/assets/images/people'
papers: '/papers'
files: '/assets/files'
